### ISSUE TITLE
Error in /

### ISSUE THREAD

**Issue by ccascone** [OpenNetworkingFoundation/cla-manager#151] opened 2020-04-12 11:32 UTC
## Error in clam-client

**Error** in **/**
A network error (such as timeout, interrupted connection or unreachable host) has occurred.

[View on Bugsnag](https://app.bugsnag.com/onf-1/clam-client/errors/5e92fc468ebe130018bfb811?event_id=5e92fc460059b54c602c0000&i=gh&m=ci)

## Stacktrace

    ../../common/node_modules/@firebase/auth/dist/auth.esm.js:913 - 

[View full stacktrace](https://app.bugsnag.com/onf-1/clam-client/errors/5e92fc468ebe130018bfb811?event_id=5e92fc460059b54c602c0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by teone** [comment] 2020-04-15 23:14
This seems to be a network timeout, not a real issue. Can't reproduce with a stable connection. Closing for now

**Closed by teone** 2020-04-15 23:14 UTC
Labels: bugsnag
